### PR TITLE
add configuration to build snap package

### PR DESCRIPTION
**Pull request by albertodonato**
This adds a `snapcraft.yaml` config to allow building a snap package for `dog`.

The snap also includes bash autocompletion.

### CODE REVIEW

**Comment by ogham** [comment]
Thanks for making a Snap config for dog. But, I have to ask: is there any way to do this without the config being in the repository? I'm wary about including packaging instructions for a system I'm not familiar with, because in the past I've included such things and then they've gone out-of-date and I never noticed.

**Comment by albertodonato** [comment]
Yes, the `snapcraft.yaml` could be in a separate repo and the conf could just point at this repo for getting the source tree (it just needs changing the `source: .` line to `source: https://github.com/ogham/dog`.

The only drawback would be that having it in the same repo means you'd get automatic builds every time something is merged to master, (see https://snapcraft.io/build). This assuming you want to register the `dog` snap.

It's fine if you don't want to merge the PR, I can just create a repo for it, and push to the store.
This was just in case you're interested in maintaining snap packaging as well.

**Comment by ogham** [comment]
Hi, sorry about the delay on this one. I still prefer to keep packaging instructions out of the repo, so you'll have to create your own one if you haven't done that already.

**Comment by albertodonato** [comment]
No problem. 

FTR it turns out there's already a `dog` snap published on the store: https://snapcraft.io/dog

**Pull request closed without merging**
