### PR TITLE
Port man-page from pandoc to scdoc

### LINKED ISSUE #3: Include generated manual page in the repository
First of all, thanks a lot for this really nice DNS client!

dog was recently packages in nixpkgs. I have opened a pull request to also add the shell completions and man page (https://github.com/NixOS/nixpkgs/pull/103192) to the Nix package. However, pandoc is a really large dependency that increases evaluation time quite a bit.

Would it be possible to include a pregenerated version of the man page (`dog.1`) in the repository as well?

### PR DESCRIPTION
**Pull request by kpcyrd**
Resolves #3 since scdoc is a much lighter dependency than pandoc. Please have a look @danieldk!

### CODE REVIEW

**Comment by danieldk** [comment]
Tested with a small change to the Nix derivation:

https://github.com/danieldk/nixpkgs/commit/3feeeee14a0807ae189a56d71dd78eb84a216029

Works like a charm and the (dependency closure) for scdoc is really small. Thanks a lot!

**Comment by vladimyr** [comment]
This is awesome! 👍 
I actually tried to do it myself just to avoid depending on `pandoc` in the brew formula, but I constantly failed to keep the original manpage layout as proper `scdoc` noob. 🙃

**Comment by ogham** [comment]
Sorry about the delay on this. After some consideration and while I appreciate that pandoc is a big dependency I decided to stick with it. I will deal with #3 by providing a man-page-and-completions-only archive so users will not have to install any generator tool.

**Comment by vladimyr** [comment]
If possible, produce release tarballs with both source code and generated manpage/s and completion/s so packagers can use a single resource.

**Comment by ogham** [comment]
I have a script that generates both `dog-v0.1.1-source-code.zip` and `dog-v0.1.1-accoutrements.zip` which should cover all the cases!

**Comment by vladimyr** [comment]
_accouterments_ 💯 🏅

**Pull request closed without merging**
